### ISSUE TITLE
Create topology documentation

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-extension-issues#11]
We should add documentation to org for how products should use Topology. This may require collaboration with design (Andrew Ronaldson)
--
Updating this comment - the checklist below will serve to track the work in this issue!

@jeff-phillips-18 and I (@jenny-s51 ) have established that the following work needs to be done, and these are currently in progress:

- [x]  Create an .md file in topology which will include the examples
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #18
- [x] #29
- [x] #17 
- [x] #26
- [x] #27
- [x] #28
- [x] #32
- [x] #33
- [x] Build a demo that shows Pipelines
- [x] Expose the types that are in the defaultNode file as PropTypes (defaultNode, defaultEdge, defaultGroup) via propTables

**Comment by jenny-s51** [comment]
The checklist below will serve to track the work in this issue!

@jeff-phillips-18 and I have established that the following work needs to be done, and these are currently in progress:

- [ ] Create an `.md` file in topology which will include the examples
- [ ] Build/document a Baseline demo to demonstrate a topology MVP to consumers
- [ ] Build/document a Custom Styles demo to demonstrate style options to consumers
- [ ] Build/document a Selection demo to demonstrate selection functionality to consumers
- [ ] Build/document a Pan/Zoom demo to demonstrate pan/zoom functionality to consumers
- [ ] Build/document a Connectors demo
- [ ] Build/document a Drag and Drop demo

**Comment by jessiehuff** [comment]
I believe that all of the topology docs have been merged - feel free to reopen if needed!
