### ISSUE TITLE
Ensure all react-* references are ^ (4.x.x)

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-extension-issues#19]
Nicole created [a sheet](https://docs.google.com/spreadsheets/d/1sOlWgUcrVVMvHajOSKB397s3lSeS-9tPgiTuQXZDz_Q/edit#gid=0) comparing the different repos and their dependencies. We should ensure that all extensions react-* references are ^ (4.x.x)

**Comment by wise-king-sullyman** [comment]
This has been done as part of the hardening efforts in the seed app, Log Viewer, Catalog View, and Console.
