### ISSUE TITLE
Pull catalog view into its own repo

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-extension-issues#2]
Remove catalog view code out of pf-react and into its own repo. Use the extensions template to test out its functionality.

**Comment by jessiehuff** [comment]
Exists in its own repo here: https://github.com/patternfly/react-catalog-view

Just needs to be removed from pf-react

**Comment by wise-king-sullyman** [comment]
It was removed from pf-react in https://github.com/patternfly/patternfly-react/pull/8474. 

Is it good to close this issue now, or do you want to wait until the package as released from the new repo gets tested at the end of this sprint?

**Comment by jessiehuff** [comment]
Nice! Ok, I think this issue is probably ok to close then. If we discover issues in testing, we could open new issues for needed work.
