### ISSUE TITLE
Extract virtualized table into its own repo

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-extension-issues#40]
Use ext seed to extract virtualized table into its own repo
- [x] make sure new issues are automatically added to PatternFly Issues Github Project board
- [ ] mark it deprecated in npm?
- [x] it should be releasing a 5.0.0-alpha.x versions on an alpha channel

pf-react team will update it to use v5 alphas later.

**Comment by nicolethoen** [comment]
@wise-king-sullyman added some success criteria - let me know if you have questions
