### ISSUE TITLE
Bug - Extensions - test v4 -> v5 collision solutions

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly-extension-issues#49]
Once the [core PR is merged](https://github.com/patternfly/patternfly/pull/5434), and [the react follow up work is completed](https://github.com/patternfly/patternfly-react/issues/8816), we need to make sure that extensions don't break when pulling in these updates.

Basically, all css class names and variables are being changed/updated for v5 as part of this effort.

**Comment by jessiehuff** [comment]
Was completed as part of V5 upgrade on all extensions repos
