### ISSUE TITLE
Audit dark theme in other extensions

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-extension-issues#50]
As part of delivering v5, we need to make sure that the existing dark theme is implemented correctly in extensions.

Part of v5 is adding the dark theme switcher to patternfly.org, so any dark theme inconsistencies in extensions will be apparent in the documentation.

**Comment by jessiehuff** [comment]
I believe that Andrew has completed his review and has compiled his feedback in [this doc](https://docs.google.com/document/d/1cvhnDIN2e93dwZvXDxrHNtFvSVPz-Hu-YgzI3XMO5kM/edit#heading=h.dmqgtheyes8t).
