### ISSUE TITLE
Connect extensions to the UXD Design Hub

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-extension-issues#52]
We should work on connecting extensions to the design hub effort.

Based on my discussions with Andrew, it likely makes sense to continue having org be the source of truth for design and development of extensions. However, the design hub is where products can share specifically how they're using extensions. We could create a portfolio called "Extensions" and house the relevant extensions information there. Andrew said that the structure of the nav might change soon though so we'll keep in touch about approach.
Our suggestion is to approach this in stages:

- Stage 1 - list the extensions, the products that use them/who is consuming it, and the contacts for the extension (essentially basic analytics)
- Stage 2 - we request that extensions designers make posts about how they're using extensions in product (the larger design piece)

**Comment by dlabaj** [comment]
Closing issue to it being stale.
