### ISSUE TITLE
Release v6 alpha omega

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-extension-issues#60]
Have builds read by may 15.  The following needs to be done to accept completeness of this issue.

- [x] All patterhfly code complete and tested,.
- [x] Any issues are resolved that where holding up the release.  These issues should be crucial.
- [x] Documentation site has been update and reviewed.
- [ ] Announcement is made on the PatternFly and uxd slack sites that the release availalbe.

**Comment by nicolethoen** [comment]
I will mark this done. An annoucement never went out, but testers were informed. The staging site needs more clean up before we widely direct people to it.
