### ISSUE TITLE
Add/Update promote.sh script for extensions.

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-extension-issues#63]
Currently react has a script that indicates the current releases to be promoted.  It would be great to have this also pull in the extensions or have a separate script for extensions.  My current recommendation is to have this be part of the promote.sh script so that all the code lives in one place.

**Comment by dlabaj** [comment]
CC: @tlabaj @nicolethoen Not sure what you think of adding this ability to the promote.sh script.

**Comment by nicolethoen** [comment]
I think this script already lives in org - we can update it if it's missing extensions:
https://github.com/patternfly/patternfly-org/blob/main/scripts/latest-versions.sh
